export const ACCOUNT_INFO_ACTION_STARTED = 'ACCOUNT_INFO_ACTION_STARTED'
export const ACCOUNT_INFO_ACTION_SUCCESS = 'ACCOUNT_INFO_ACTION_SUCCESS' 
export const ACCOUNT_INFO_ACTION_FAILED = 'ACCOUNT_INFO_ACTION_FAILED' 